CREATE DATABASE IF NOT EXISTS CAPSTONE_DB;
CREATE SCHEMA IF NOT EXISTS CAPSTONE_DB.CELL_TOWER;
USE DATABASE CAPSTONE_DB;
USE SCHEMA CELL_TOWER;

CREATE OR REPLACE FILE FORMAT CSV_FF
TYPE=CSV SKIP_HEADER=1 FIELD_OPTIONALLY_ENCLOSED_BY='"' NULL_IF=('NULL','');

CREATE OR REPLACE STAGE CAPSTONE_STAGE FILE_FORMAT=CSV_FF;

CREATE OR REPLACE TABLE GOLD_TOWER_HOUR (
    TOWER_ID VARCHAR,
    SITE_NAME VARCHAR,
    CITY VARCHAR,
    DISTRICT VARCHAR,
    CAPACITY_CHANNELS NUMBER,
    CALL_DATE DATE,
    HOUR_OF_DAY NUMBER,
    CALLS NUMBER,
    DROPPED_CALLS NUMBER,
    DROP_RATE FLOAT,
    PEAK_CONCURRENT NUMBER,
    UTILISATION FLOAT,
    AVG_DURATION_SECONDS FLOAT
);

-- Upload the single exported Gold CSV to @CAPSTONE_STAGE before running COPY INTO.
COPY INTO GOLD_TOWER_HOUR
FROM @CAPSTONE_STAGE
FILE_FORMAT=(FORMAT_NAME=CSV_FF)
PATTERN='.*[.]csv([.]gz)?'
ON_ERROR='ABORT_STATEMENT';

-- Q1: worst hour per tower.
WITH th AS (
    SELECT TOWER_ID,HOUR_OF_DAY,SUM(CALLS) CALLS,SUM(DROPPED_CALLS) DROPS
    FROM GOLD_TOWER_HOUR
    GROUP BY TOWER_ID,HOUR_OF_DAY
)
SELECT TOWER_ID,HOUR_OF_DAY,CALLS,DROPS,
       ROUND(100*DROPS/NULLIF(CALLS,0),2) WORST_HOUR_PCT,
       ROUND(100*SUM(DROPS) OVER(PARTITION BY TOWER_ID) /
             NULLIF(SUM(CALLS) OVER(PARTITION BY TOWER_ID),0),2) TOWER_PCT
FROM th
QUALIFY ROW_NUMBER() OVER(
    PARTITION BY TOWER_ID
    ORDER BY DROPS/NULLIF(CALLS,0) DESC,HOUR_OF_DAY
)=1
ORDER BY WORST_HOUR_PCT DESC;

-- Q2: towers above 5% on more than 10 days.
WITH daily AS (
    SELECT TOWER_ID,CALL_DATE,SUM(CALLS) CALLS,SUM(DROPPED_CALLS) DROPS
    FROM GOLD_TOWER_HOUR
    GROUP BY TOWER_ID,CALL_DATE
)
SELECT TOWER_ID,
       COUNT_IF(DROPS/NULLIF(CALLS,0)>0.05) DAYS_ABOVE_5_PCT
FROM daily
GROUP BY TOWER_ID
HAVING COUNT_IF(DROPS/NULLIF(CALLS,0)>0.05)>10
ORDER BY DAYS_ABOVE_5_PCT DESC;

-- Q3: relationship with concurrent calls.
SELECT PEAK_CONCURRENT,
       SUM(CALLS) CALLS,
       SUM(DROPPED_CALLS) DROPS,
       ROUND(100*SUM(DROPPED_CALLS)/NULLIF(SUM(CALLS),0),2) DROP_RATE_PCT
FROM GOLD_TOWER_HOUR
GROUP BY PEAK_CONCURRENT
ORDER BY PEAK_CONCURRENT;

SELECT COUNT(*) GOLD_ROWS,
       SUM(CALLS) TOTAL_CALLS,
       SUM(DROPPED_CALLS) TOTAL_DROPS,
       ROUND(100*SUM(DROPPED_CALLS)/NULLIF(SUM(CALLS),0),2) OVERALL_DROP_RATE
FROM GOLD_TOWER_HOUR;
